name: Node.js CI/CD

on:
  push:
    branches: 
      - '**'  # Toutes les branches
  pull_request:
    branches:
      - '**'  # Toutes les branches
  workflow_dispatch:  # Déclenchement manuel

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest  # Utilisation d'un runner hébergé par GitHub; changez en 'self-hosted' si nécessaire

    strategy:
      matrix:
        node-version: [16.x, 18.x]  # Tester sur plusieurs versions de Node.js

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Utilisation de la dernière version stable

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Activer le cache pour accélérer les installations

      - name: Install Dependencies
        run: npm ci  # Utiliser 'npm ci' pour des installations plus rapides et fiables

      - name: Lint Code
        run: npm run lint  # Assurez-vous d'avoir un script 'lint' dans votre package.json

      - name: Run Tests
        run: npm test

      - name: Generate Code Coverage
        run: npm run coverage  # Assurez-vous d'avoir un script 'coverage'

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/  # Adapter selon le dossier de sortie de votre couverture

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/  # Adapter selon le dossier de sortie de vos tests

  deploy:
    name: Deploy to Production
    needs: build-and-test
    runs-on: self-hosted  # Utiliser un runner auto-hébergé pour le déploiement
    if: >
      github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build  # Assurez-vous d'avoir un script 'build'

      - name: Deploy with PM2
        env:
          PM2_HOME: /home/runner/.pm2  # Définir PM2_HOME si nécessaire
        run: |
          # Arrêter l'application si elle est en cours d'exécution
          pm2 stop app-name || true
          # Démarrer l'application avec PM2
          pm2 start app.js --name app-name --watch
          # Sauvegarder la configuration PM2 pour persistance
          pm2 save

      - name: Notify Deployment Success
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.createComment({
              issue_number: 1,  # Remplacez par le numéro de l'issue ou utilisez une autre méthode de notification
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Déploiement en production réussi !'
            })
